# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 991, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1001, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setMaximumSize(QtCore.QSize(1001, 16777215))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(10, 180, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(10, 180, 0))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(10, 180, 0))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(10, 180, 0))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(10, 180, 0))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(10, 180, 0))
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setBaseSize(QtCore.QSize(50, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_host = QtWidgets.QAction(MainWindow)
        self.action_host.setCheckable(True)
        self.action_host.setObjectName("action_host")      
        self.action_host.setIcon(QtGui.QIcon('icons\\action_host.png'))
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setCheckable(True)
        self.action_new.setObjectName("action_new")
        self.action_new.setIcon(QtGui.QIcon('icons\\action_new.png'))
        self.action_star = QtWidgets.QAction(MainWindow)
        self.action_star.setCheckable(True)
        self.action_star.setIcon(QtGui.QIcon('icons\\action_star.png'))
        self.action_star.setObjectName("action_star")
        self.action_china = QtWidgets.QAction(MainWindow)
        self.action_china.setCheckable(True)
        self.action_china.setIcon(QtGui.QIcon('icons\\action_china.png'))
        self.action_china.setObjectName("action_china")
        self.action_us = QtWidgets.QAction(MainWindow)
        self.action_us.setCheckable(True)
        self.action_us.setIcon(QtGui.QIcon('icons\\action_us.png'))
        self.action_us.setObjectName("action_us")
        self.action_act = QtWidgets.QAction(MainWindow)
        self.action_act.setCheckable(True)
        self.action_act.setObjectName("action_act")
        self.action_act.setIcon(QtGui.QIcon('icons\\action_act.png'))
        self.action_happy = QtWidgets.QAction(MainWindow)
        self.action_happy.setCheckable(True)
        self.action_happy.setIcon(QtGui.QIcon('icons\\action_happy.png'))
        self.action_happy.setObjectName("action_happy")
        self.action_love = QtWidgets.QAction(MainWindow)
        self.action_love.setCheckable(True)
        self.action_love.setObjectName("action_love")
        self.action_love.setIcon(QtGui.QIcon('icons\\action_love.png'))
        self.action_sc = QtWidgets.QAction(MainWindow)
        self.action_sc.setCheckable(True)
        self.action_sc.setObjectName("action_sc")
        self.action_sc.setIcon(QtGui.QIcon('icons\\action_sc.png'))
        self.action_what = QtWidgets.QAction(MainWindow)
        self.action_what.setObjectName("action_what")
        self.action_what.setIcon(QtGui.QIcon('icons\\action_what.png'))
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.action_host)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_new)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_star)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_china)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_us)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_act)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_happy)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_love)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_sc)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_what)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "菜鸟学python数据库实战"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "序号"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "年份"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "国家"))
        # item = self.tableWidget.horizontalHeaderItem(3)
        # item.setText(_translate("MainWindow", "评分"))
        # item = self.tableWidget.horizontalHeaderItem(4)
        # item.setText(_translate("MainWindow", "电影名称"))
        # item = self.tableWidget.horizontalHeaderItem(5)
        # item.setText(_translate("MainWindow", "电影描述"))
        
        self.menu.setTitle(_translate("MainWindow", "更新(&F)"))
        self.menu_2.setTitle(_translate("MainWindow", "退出(&Q)"))
        self.menu_3.setTitle(_translate("MainWindow", "关于(&A)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_host.setText(_translate("MainWindow", "热门"))
        self.action_host.setToolTip(_translate("MainWindow", "热门电影"))
        self.action_host.setShortcut(_translate("MainWindow", "F1"))
        self.action_new.setText(_translate("MainWindow", "最新"))
        self.action_new.setToolTip(_translate("MainWindow", "最新电影"))
        self.action_new.setShortcut(_translate("MainWindow", "F2"))
        self.action_star.setText(_translate("MainWindow", "经典"))
        self.action_star.setShortcut(_translate("MainWindow", "F3"))
        self.action_china.setText(_translate("MainWindow", "华语"))
        self.action_china.setToolTip(_translate("MainWindow", "华语电影"))
        self.action_china.setShortcut(_translate("MainWindow", "F4"))
        self.action_us.setText(_translate("MainWindow", "欧美 "))
        self.action_us.setToolTip(_translate("MainWindow", "欧美 "))
        self.action_us.setShortcut(_translate("MainWindow", "F5"))
        self.action_act.setText(_translate("MainWindow", "动作 "))
        self.action_act.setToolTip(_translate("MainWindow", "动作"))
        self.action_act.setShortcut(_translate("MainWindow", "F6"))
        self.action_happy.setText(_translate("MainWindow", "喜剧 "))
        self.action_happy.setToolTip(_translate("MainWindow", "喜剧 "))
        self.action_happy.setShortcut(_translate("MainWindow", "F7"))
        self.action_love.setText(_translate("MainWindow", "爱情"))
        self.action_love.setToolTip(_translate("MainWindow", "爱情"))
        self.action_sc.setText(_translate("MainWindow", "科幻 "))
        self.action_sc.setToolTip(_translate("MainWindow", "科幻"))
        self.action_what.setText(_translate("MainWindow", "悬疑"))
        self.action_what.setToolTip(_translate("MainWindow", "悬疑"))

